name: soul_script_reader
description: "타로 카드 뽑기 및 해석 히스토리 앱"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^17.3.0
  flutter_riverpod: ^2.6.1
  flutter_dotenv: ^6.0.1
  dio: ^5.8.0+1
  freezed_annotation: ^3.1.0
  json_annotation: ^4.12.0
  intl: ^0.20.2
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.15.0
  freezed: ^3.2.5
  json_serializable: ^6.14.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/logo/
